# Site settings
title: "bapu.bhimasani.com"
page_title: "My Bapu - bapu.bhimasani.com"
email: 16abhimasani@gmail.com
description: "In the memory of my father Sri. Bhimasani Harinarayan who passed away on Sep 10th 2016"

# Server
baseurl: ""
destination: _site
host: 0.0.0.0
port: 4001
url: http://bapu.bhimasani.com
encoding: UTF-8

# Excludes
exclude: ["node_modules", "Gemfile", "Gemfile.lock", "commit-hook.sh", "package.json"]

# URLs
permalink: pretty

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Repo
repo: https://github.com/bapu-bhimasani/bapu-bhimasani.github.io
